"""
Email tool for sending emails via SMTP.
"""
import smtplib
from email.mime.text import MIMEText
from typing import Optional
from langchain_core.tools import tool
from config.constants import CONFIG
from tools.timing_tracker import timing_tracker


@tool
def send_email(subject: str, body: str) -> str:
    """
    Send an email with the given subject and body.
    
    Args:
        subject: The email subject line
        body: The email body content
        
    Returns:
        Success or error message
    """
    timing_tracker.start_timer("send_email")
    
    try:
        print(f"📤 [EMAIL] Sending email with subject: {subject}")
        
        # Create the email message
        msg = MIMEText(body)
        msg["Subject"] = subject
        msg["From"] = CONFIG["SENDER_EMAIL"]
        msg["To"] = CONFIG["RECEIVER_EMAIL"]
        
        # Send the email
        with smtplib.SMTP_SSL(CONFIG["SMTP_SERVER"], CONFIG["SMTP_PORT"]) as server:
            server.login(CONFIG["SENDER_EMAIL"], CONFIG["SENDER_PASSWORD"])
            server.sendmail(CONFIG["SENDER_EMAIL"], CONFIG["RECEIVER_EMAIL"], msg.as_string())
            
        success_msg = f"✅ Email sent successfully to {CONFIG['RECEIVER_EMAIL']}"
        print(f"📤 [EMAIL] {success_msg}")
        timing_tracker.stop_timer("send_email")
        return success_msg
        
    except smtplib.SMTPAuthenticationError:
        error_msg = "❌ Email authentication failed. Check your email credentials."
        print(f"📤 [EMAIL] {error_msg}")
        timing_tracker.stop_timer("send_email")
        return error_msg
        
    except smtplib.SMTPException as e:
        error_msg = f"❌ SMTP error sending email: {str(e)}"
        print(f"📤 [EMAIL] {error_msg}")
        timing_tracker.stop_timer("send_email")
        return error_msg
        
    except Exception as e:
        error_msg = f"❌ Unexpected error sending email: {str(e)}"
        print(f"📤 [EMAIL] {error_msg}")
        timing_tracker.stop_timer("send_email")
        return error_msg


def validate_email_config() -> bool:
    """
    Validate that email configuration is properly set up.
    
    Returns:
        True if all required email config is present, False otherwise
    """
    required_fields = ["SENDER_EMAIL", "SENDER_PASSWORD", "RECEIVER_EMAIL"]
    return all(CONFIG.get(field) for field in required_fields)


def get_email_patterns() -> list[str]:
    """
    Get list of email-related keywords for intent recognition.
    
    Returns:
        List of email-related keywords
    """
    return [
        'email', 'send', 'mail', 'notify', 'message', 'inform',
        'e-mail', 'contact', 'report', 'update'
    ]


def format_weather_email(weather_data: str, subject: Optional[str] = None) -> tuple[str, str]:
    """
    Format weather data into a professional email.
    
    Args:
        weather_data: Raw weather information string
        subject: Optional custom subject line
        
    Returns:
        Tuple of (subject, formatted_body)
    """
    if not subject:
        subject = "Weather Report"
        
    body = f"""Dear User,

Here is the weather information you requested:

{weather_data}

This information was automatically generated by your multi-agent weather system.

Best regards,
Weather Agent
"""
    return subject, body 